info:
  component: Player Stats (Local Properties)

server:
  port: ${PORT:8081}

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

hystrix:
  enabled: true
  streamEnabled: true
  streamUrl: /hystrix.stream
  stream:
    bus:
      enabled: true
      sendRate: 600

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
      #naming_strategy: org.hibernate.cfg.EJB3NamingStrategy #Camel-case JPA naming
  datasource:
    url: ${DATASOURCE_URI:jdbc:mysql://localhost/player-stats-service}
    username: playerstats_user
    password: abc123
    driver-class-name: com.mysql.jdbc.Driver

---

spring:
  profiles: cloud

eureka:
  instance:
    preferIpAddress: false